### ISSUE TITLE
Use MAE pretrained model

### ISSUE THREAD

**Issue by junkunyuan** [YanzuoLu/MALE#2]
Hi, I use the official pretrained model of MAE-B for finetuning. 

```bash
python \
main_finetune.py \
--config_file configs/finetune/Market-1501/mae_inet_lup_vitb_ep800_ratio_optimized/baseline.yaml
```
And the `baseline.yaml` is :
```python
MODEL:
  CHECKPOINT_PATH: 'mae_pretrain_vit_base.pth'

DATASET:
  NAME: Market1501
  ROOT_DIR: '../market1501/'

OUTPUT_DIR: 'runs/finetune/Market-1501/mae_inet_vitb_ep800_ratio_optimized/baseline'
```
And I encounter the error in loading position embedding:
```base
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 197, 768]) from checkpoint, the shape in current model is torch.Size([1, 129, 768]).
```
What should I do?

**Comment by YanzuoLu** [comment]
I probably haven't tried to use mae's pre-trained weights directly for finetune. I don't know if the weights are common here. You can try to modify the parameters [MODEL.CHECKPOINT_POS_EMBED_SIZE](https://github.com/YanzuoLu/MALE/blob/main/conf_finetune.py#L16) to make the positional embedding aligned, because the error message seems that the weight is prepared for the 256x256 imagenet image.

**Comment by junkunyuan** [comment]
Sorry, I may misunderstand your results.

I want to know how to reproduce the results in the first line of Table 4?

Thanks very much!

**Comment by YanzuoLu** [comment]
I mean I have not used this mae_pretrain_vit_base.pth you showed, in fact MAE provides pretrained weights with decoder part as [mae_pretrain_vit_base_full.pth](https://github.com/facebookresearch/mae/issues/8#issuecomment-1009377423) in my baidudisk folder. Please refer to [baseline.yaml](https://github.com/YanzuoLu/MALE/blob/main/configs/finetune/MSMT17/mae_in1k_vitb_ep1600/baseline.yaml) for more details if you want to train with Market-1501, in which I set CHECKPOINT_POS_EMBED_SIZE as (14, 14). This should help you.
