### ISSUE TITLE
About timm version

### ISSUE THREAD

**Issue by junkunyuan** [YanzuoLu/MALE#3]
Hi, I set timm=0.6.12 by following the environment below.

https://github.com/YanzuoLu/MALE/blob/b28510383e3a1eb050e4ad5e611e86ddbd4d45a3/environment.yaml#L15

But I encountered an error that reported "head_dist is not in VisionTransformer class".

I see that "head_dist" was removed since timm=0.6.5.

Could you fix this problem?

**Comment by YanzuoLu** [comment]
Sorry, I found this problem before and modified the version of timm in my own environment, but forgot to modify the environment file. You can try to install [timm==0.5.4](https://github.com/YanzuoLu/MALE/blob/main/environment.yaml#L15), it should be no problem.

**Comment by junkunyuan** [comment]
Thanks!
